### PR TITLE
Requested fixes

### PR DESCRIPTION
**Pull request by marcinbujar**
- Fixed organisation request additional details not being saved and displayed
- Fixed not being able to view device passwords
- Added ID to organisation label on device page for distinguishing multiple requests from the same org
- Fixed header on the become a volunteer page
- Added missing device-specific checkboxes on the device page options section

### CODE REVIEW

**Review by OthmanHackIt — APPROVED** [review]
/approve

**Review by OthmanHackIt — APPROVED** [review]
/approve

**Review by stevejuma — APPROVED** [review]
LGTM

**Pull request merged**
